### ISSUE TITLE
Adding grape-swagger-entity to Gemfile still throws GrapeSwagger::Errors::UnregisteredParser error

### ISSUE THREAD

**Issue by stefan-kolb** [ruby-grape/grape-swagger#424] opened 2016-05-17 14:40 UTC
Introduced by #420 

Generation of swagger spec was working fine for grape-swagger < 0.20.4.
After 0.20.4 it throws GrapeSwagger::Errors::UnregisteredParser error, as expected.
Adding the new extracted Gem grape-swagger-entity to my Gemfile still throws GrapeSwagger::Errors::UnregisteredParser error.
Am I missing something here? My models just inherit from Grape::Entity.
Somehow, the Parsers just don't get registered for me.

**Comment by Bugagazavr** [comment] 2016-05-17 15:06
grape-swagger tested with `grape-entity`, and tests is passed, if you use non rails application, you should require `grape-swagger/entity` when your application initialized.

```rb
# My Gemfile
gem 'grape-swagger', '~> 0.20.4'
gem 'grape-swagger-entity', '~> 0.1.3'
gem 'grape-swagger-representable', '~> 0.1.3'
```

```
[2] pry(main)> GrapeSwagger.model_parsers.to_a
[
    [0] [
        [0] GrapeSwagger::Entity::Parser < Object,
        [1] "Grape::Entity"
    ],
    [1] [
        [0] GrapeSwagger::Representable::Parser < Object,
        [1] "Representable::Decorator"
    ]
]
```

Feel free if you have any questions.

**Comment by stefan-kolb** [comment] 2016-05-17 15:13
Requiring 'grape-swagger/entity' was the problem and solved my issue. Whereas I see the added benefit by extracting the parser logic for different entity implementations, there are additional pain points for customers getting this to work. But probably there is no easier solution to get this working. You should definately add a comment that one needs to require `grape-swagger/entity` to the initialization logic for non rails apps inside the documentation https://github.com/ruby-grape/grape-swagger#model-parsers!

Thanks for your quick reply :smile: !

**Comment by dblock** [comment] 2016-05-17 16:29
I think it's fixable whereas the grape-swagger-entity gem should `require` all the right things.

**Comment by stefan-kolb** [comment] 2016-05-17 16:44
Seems like a good idea :+1:

**Comment by stefan-kolb** [comment] 2016-05-17 19:59
@dblock The problem is that the parser must be registered, i.e., this line of code inside `grape-swagger/entity` must be executed:
`GrapeSwagger.model_parsers.register(::GrapeSwagger::Entity::Parser, ::Grape::Entity)`
Which is only done when requiring the wanted parser implementation for non-rails apps.

**Comment by dblock** [comment] 2016-05-18 10:57
@stefan-kolb I've dealt with similar things in the past :) Do you think you can build a very simple repro of this problem in a project? I can try to fix.

**Comment by stefan-kolb** [comment] 2016-05-18 11:57
@dblock Take a look at this example: https://github.com/stefan-kolb/grape-parser-demo
Without the uncommented require inside `api.rb` the previously mentioned code does not get executed and therefore the parser is missing.

**Comment by dblock** [comment] 2016-05-20 18:40
You can fix your project by basically calling `Bundler.require` in `config.ru` and then there's no explicit `require` necessary. 

This is because you're not requiring things that are in your Gemfile, Rails [does that for you](https://github.com/rails/rails/blob/52ce6ece8c8f74064bb64e0a0b1ddd83092718e1/railties/lib/rails/generators/rails/app/templates/config/application.rb#L21). 

We could improve things by requiring every possibly 3rd party parser in  grape-swagger and ignoring failures, but that would be backwards, so I'd rather not.

I'm going to close this as by design. Thanks for bringing this up, hope this helps!

**Closed by dblock** 2016-05-20 18:40 UTC

**Comment by stefan-kolb** [comment] 2016-05-21 07:32
@dblock Thanks for your efforts! I absolutely second your arguments. Nevertheless, I added a small hint inside the README so that user can easily omit that small pitfall.
