### ISSUE TITLE
suffix with json not work, with add_swagger_documentation default option.

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape-swagger#244] opened 2015-04-08 02:11 UTC
in project `grape-swagger-0.10.1/example` folder:

``` bash
$ ls
api.rb      config.ru   splines.png

$ rackup config.ru
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/grape-swagger-0.10.1/example/api.rb:4: warning: class variable access from toplevel
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:9292, CTRL+C to stop

$ curl http://localhost:9292/swagger_doc/swagger_doc.json
Not Found

$ curl http://localhost:9292/swagger_doc/swagger_doc

{"apiVersion":"0.1","swaggerVersion":"1.2","resourcePath":"/swagger_doc","produces":["application/json"],"apis":[{"path":"/swagger_doc","operations":[{"notes":"","summary":"Swagger compatible API description","nickname":"GET-swagger_doc","method":"GET","parameters":[],"type":"void"}]},{"path":"/swagger_doc/{name}","operations":[{"notes":"","summary":"Swagger compatible API description for specific API","nickname":"GET-swagger_doc--name","method":"GET","parameters":[{"paramType":"path","name":"name","description":"Resource name of mounted API","type":"string","required":true,"allowMultiple":false}],"type":"void"}]}],"basePath":"http://localhost:9292"}%
```

If I add the`format: :json` to `add_swagger_documentation` it will works with swagger-ui.

**Comment by dblock** [comment] 2015-04-08 11:14
This is by design, but has been causing a lot of issues, see https://github.com/intridea/grape/issues/914. Can you please PR the fix for this repo for the demo?

**Comment by LeFnord** [comment] 2017-01-14 00:32
solved in the actual version

**Closed by LeFnord** 2017-01-14 00:32 UTC
Labels: confirmed bug, swagger-1.2
